install: 
    - cinst -y pester
    - git clone https://github.com/PowerShell/DscResource.Tests
    - git clone https://github.com/PowerShell/xDSCResourceDesigner

build: false

test_script:
    - ps: |
        Import-Module .\xDSCResourceDesigner
        # We want to test dev version of the resource.
        # xDscResouceDesigner works against standart PowerShell modules path.
        # We need to make sure that root folder of xActiveDirectory is at the first place in $env:PSModulePath
        if (($env:PSModulePath.Split(';') | select -First 1) -ne $pwd) {
            $env:PSModulePath = "$pwd;$env:PSModulePath"
        }
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
on_finish:
    - ps: |
        $stagingDirectory = (Resolve-Path ..).Path
        $zipFile = Join-Path $stagingDirectory "$(Split-Path $pwd -Leaf).zip"
        Add-Type -assemblyname System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory($pwd, $zipFile)
        @(
            # You can add other artifacts here
            (ls $zipFile)
        ) | % { Push-AppveyorArtifact $_.FullName }

